# CSCI82 - Adherence Project

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
import numpy as np

## 1. Import Data

In [2]:
out_1 = pd.read_csv('coherent-11_07-22/medications.csv')
out_1 = out_1[out_1.DESCRIPTION.str.contains('statin')]
pat_1 = pd.read_csv('coherent-11_07-22/patients.csv')
statin_df = pd.merge(out_1,pat_1,how='left',right_on='Id', left_on='PATIENT')

In [3]:
len(statin_df)

30669

In [4]:
statin_df

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,2015-02-01T02:13:44Z,2021-01-30T02:13:44Z,b24e154c-14c4-8372-2b52-a466bc9b44fe,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,05d5de6e-e8bb-c0d9-8de4-29e09ea8342c,314231,Simvastatin 10 MG Oral Tablet,0.02,0.0,10,...,Pinehurst Massachusetts US,484 Cruickshank Underpass,Malden,Massachusetts,Middlesex County,2155.0,42.464574,-71.131602,28809.79,0.00
1,2016-02-01T02:13:44Z,2017-01-31T02:13:44Z,b24e154c-14c4-8372-2b52-a466bc9b44fe,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,f8444c18-3cdd-013f-0e6e-3995a96a74b6,314231,Simvastatin 10 MG Oral Tablet,0.02,0.0,12,...,Pinehurst Massachusetts US,484 Cruickshank Underpass,Malden,Massachusetts,Middlesex County,2155.0,42.464574,-71.131602,28809.79,0.00
2,2017-01-31T02:13:44Z,2018-01-31T02:13:44Z,b24e154c-14c4-8372-2b52-a466bc9b44fe,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,28a2c5c1-2c4d-0dc8-f931-0cea504604e3,314231,Simvastatin 10 MG Oral Tablet,0.02,0.0,12,...,Pinehurst Massachusetts US,484 Cruickshank Underpass,Malden,Massachusetts,Middlesex County,2155.0,42.464574,-71.131602,28809.79,0.00
3,2018-01-31T02:13:44Z,2019-01-31T02:13:44Z,b24e154c-14c4-8372-2b52-a466bc9b44fe,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,d3121917-ab5f-3921-ccb1-dd4537caaac1,314231,Simvastatin 10 MG Oral Tablet,0.02,0.0,12,...,Pinehurst Massachusetts US,484 Cruickshank Underpass,Malden,Massachusetts,Middlesex County,2155.0,42.464574,-71.131602,28809.79,0.00
4,2019-01-31T02:13:44Z,2020-01-31T02:13:44Z,b24e154c-14c4-8372-2b52-a466bc9b44fe,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,a570db43-fb48-520d-edab-4f565320e86a,314231,Simvastatin 10 MG Oral Tablet,0.02,0.0,12,...,Pinehurst Massachusetts US,484 Cruickshank Underpass,Malden,Massachusetts,Middlesex County,2155.0,42.464574,-71.131602,28809.79,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30664,2020-12-27T15:39:54Z,2021-04-04T15:39:54Z,3107760e-1dce-a177-4122-725241aae61a,7caa7254-5050-3b5e-9eae-bd5ea30e809c,5b003d8c-f311-ddf9-2bf9-e93a875d8123,312961,Simvastatin 20 MG Oral Tablet,29.73,0.0,3,...,Toulouse Occitanie FR,640 Wiegand Gardens,Green Harbor-Cedar Crest,Massachusetts,Plymouth County,NaN,42.112170,-70.696235,2099913.03,297590.59
30665,2021-04-04T15:39:54Z,2021-05-02T15:39:54Z,3107760e-1dce-a177-4122-725241aae61a,7caa7254-5050-3b5e-9eae-bd5ea30e809c,1b81c1c6-5f01-8424-11c8-948604e22ebb,312961,Simvastatin 20 MG Oral Tablet,4.78,0.0,1,...,Toulouse Occitanie FR,640 Wiegand Gardens,Green Harbor-Cedar Crest,Massachusetts,Plymouth County,NaN,42.112170,-70.696235,2099913.03,297590.59
30666,2021-05-02T15:39:54Z,2021-05-30T15:39:54Z,3107760e-1dce-a177-4122-725241aae61a,7caa7254-5050-3b5e-9eae-bd5ea30e809c,a6662371-e069-40bd-6c8c-7c452fa2002a,312961,Simvastatin 20 MG Oral Tablet,35.21,0.0,1,...,Toulouse Occitanie FR,640 Wiegand Gardens,Green Harbor-Cedar Crest,Massachusetts,Plymouth County,NaN,42.112170,-70.696235,2099913.03,297590.59
30667,2021-05-30T15:39:54Z,2021-06-20T15:39:54Z,3107760e-1dce-a177-4122-725241aae61a,7caa7254-5050-3b5e-9eae-bd5ea30e809c,c0cdc8eb-62a3-50ec-3e4d-a4d0e4e0046d,312961,Simvastatin 20 MG Oral Tablet,7.53,0.0,1,...,Toulouse Occitanie FR,640 Wiegand Gardens,Green Harbor-Cedar Crest,Massachusetts,Plymouth County,NaN,42.112170,-70.696235,2099913.03,297590.59
30668,2021-06-20T15:39:54Z,NaN,3107760e-1dce-a177-4122-725241aae61a,7caa7254-5050-3b5e-9eae-bd5ea30e809c,9b825c4b-af96-b8ba-7de1-09fc9f8b5ef8,312961,Simvastatin 20 MG Oral Tablet,45.04,0.0,1,...,Toulouse Occitanie FR,640 Wiegand Gardens,Green Harbor-Cedar Crest,Massachusetts,Plymouth County,NaN,42.112170,-70.696235,2099913.03,297590.59

In [5]:
#QA Step
len(statin_df.PATIENT.unique()),len(statin_df)

(1127, 30669)

In [6]:
#Parse out dates from Start and Stop fields
statin_df['START_DAY'] = statin_df.START.str.split('T')
statin_df['START_DAY'] = [i[0] for i in statin_df['START_DAY']]

statin_df['STOP_DAY'] = statin_df.STOP.str.split('T')
statin_df['STOP_DAY'] = ['2021-07-31' if a == True else b[0] for a,b in zip(pd.isnull(statin_df.STOP_DAY),statin_df.STOP_DAY)]

#Convert dates to date time:
statin_df.START_DAY = pd.to_datetime(statin_df.START_DAY,format="%Y-%d-%m",errors='ignore')
statin_df.STOP_DAY = pd.to_datetime(statin_df.STOP_DAY,format="%Y-%d-%m",errors='ignore')

statin_df.BIRTHDATE = pd.to_datetime(statin_df.BIRTHDATE,format="%Y-%d-%m",errors='ignore')
statin_df.DEATHDATE = pd.to_datetime(statin_df.DEATHDATE,format="%Y-%d-%m",errors='ignore')

In [7]:
#Retain only fields of interest
retain=['PATIENT', 'CODE', 'DESCRIPTION',
        'DISPENSES', 'TOTALCOST', 'REASONCODE',
       'REASONDESCRIPTION','BIRTHDATE', 'DEATHDATE', 
        'RACE', 'GENDER','HEALTHCARE_EXPENSES',
       'HEALTHCARE_COVERAGE', 'START_DAY', 'STOP_DAY']

statin_df = statin_df.loc[:,retain]

statin_df

,PATIENT,CODE,DESCRIPTION,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,RACE,GENDER,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,START_DAY,STOP_DAY
0,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,10,0.20,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.00,2015-02-01,2021-01-30
1,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.00,2016-02-01,2017-01-31
2,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.00,2017-01-31,2018-01-31
3,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.00,2018-01-31,2019-01-31
4,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.00,2019-01-31,2020-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30664,3107760e-1dce-a177-4122-725241aae61a,312961,Simvastatin 20 MG Oral Tablet,3,89.19,NaN,NaN,1922-11-05,NaN,white,M,2099913.03,297590.59,2020-12-27,2021-04-04
30665,3107760e-1dce-a177-4122-725241aae61a,312961,Simvastatin 20 MG Oral Tablet,1,4.78,NaN,NaN,1922-11-05,NaN,white,M,2099913.03,297590.59,2021-04-04,2021-05-02
30666,3107760e-1dce-a177-4122-725241aae61a,312961,Simvastatin 20 MG Oral Tablet,1,35.21,NaN,NaN,1922-11-05,NaN,white,M,2099913.03,297590.59,2021-05-02,2021-05-30
30667,3107760e-1dce-a177-4122-725241aae61a,312961,Simvastatin 20 MG Oral Tablet,1,7.53,NaN,NaN,1922-11-05,NaN,white,M,2099913.03,297590.59,2021-05-30,2021-06-20
30668,3107760e-1dce-a177-4122-725241aae61a,312961,Simvastatin 20 MG Oral Tablet,1,45.04,NaN,NaN,1922-11-05,NaN,white,M,2099913.03,297590.59,2021-06-20,2021-07-31

**QA of Key Data Fields**

In [8]:
statin_df.RACE.unique()

array(['white', 'black', 'asian', 'native'], dtype=object)

In [9]:
statin_df.RACE.unique()

array(['white', 'black', 'asian', 'native'], dtype=object)

In [10]:
statin_df.DISPENSES.unique()

array([ 10,  12,   1,   7,   3,   9,   5,  11,   4,   2,   6,   8,  52,
        16, 195, 271,  28,  23,  15], dtype=int64)

In [11]:
#Remove patients dispenses >24 --> most prescriptions are one year, but allow a 2x times general

patient_list = [j if i>24 else 0 for i,j in zip(statin_df.DISPENSES,statin_df.PATIENT)] 

patient_list = list(filter(None, patient_list))

#Drop the list of patients from the data from
mask = ~statin_df['PATIENT'].isin(patient_list)
statin_df = statin_df[mask]

len(patient_list)

4

In [12]:
statin_df.DISPENSES.sum()

302873

In [13]:
#Remove patients dispenses >1 

patient_list = [j if i>24 else 0 for i,j in zip(statin_df.DISPENSES,statin_df.PATIENT)] 

patient_list = list(filter(None, patient_list))

#Drop the list of patients from the data from
mask = ~statin_df['PATIENT'].isin(patient_list)
statin_df = statin_df[mask]

len(patient_list)

0

In [14]:
zero = statin_df.groupby('PATIENT').sum().loc[:,'DISPENSES']
zero = pd.DataFrame(zero)

count = zero[zero.DISPENSES != 0]

count

C:\Users\erinr\AppData\Local\Temp\ipykernel_19964\1306926202.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  zero = statin_df.groupby('PATIENT').sum().loc[:,'DISPENSES']

                                      DISPENSES
PATIENT
0074596f-5fd0-7965-db0f-cce71c81567d        454
008d8e1d-c53f-47ac-fc06-aeb02ea5e3ec         82
00a4a086-309e-58e2-9bdc-ead0f5c88ae6         58
013695bb-e8dd-a6cc-3bdf-14a1b4e107fb        153
01541ad3-5323-cb64-96a7-c2ef42941253         71
...                                         ...
fedcaae9-b81d-3edc-1d74-6af9b3a06dcf        135
fef2a0da-fe27-8003-c075-09e3bc269107        418
ff02f656-69fd-efe9-0402-8daa260e54a7         82
ffba6020-d2c0-0227-e4b8-80a319375339        130
ffce3431-ba26-7d3a-2d71-08adce6d5927        214

[1123 rows x 1 columns]

In [15]:
statin_df.DISPENSES.unique()

array([10, 12,  1,  7,  3,  9,  5, 11,  4,  2,  6,  8, 16, 23, 15],
      dtype=int64)

In [16]:
statin_df.REASONDESCRIPTION.unique()

array(['Hyperlipidemia', nan], dtype=object)

In [17]:
statin_df.DESCRIPTION.unique()

array(['Simvastatin 10 MG Oral Tablet', 'Simvastatin 20 MG Oral Tablet',
       'Atorvastatin 80 MG Oral Tablet'], dtype=object)

In [18]:
profile = statin_df.groupby('CODE').sum()

profile = profile.iloc[:,0]

profile

C:\Users\erinr\AppData\Local\Temp\ipykernel_19964\326273538.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  profile = statin_df.groupby('CODE').sum()

CODE
259255       128
312961     57343
314231    245402
Name: DISPENSES, dtype: int64

In [19]:
reason_profile = statin_df.groupby('REASONCODE').sum();
reason_profile = reason_profile.iloc[:,1]
reason_profile

C:\Users\erinr\AppData\Local\Temp\ipykernel_19964\3141128310.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  reason_profile = statin_df.groupby('REASONCODE').sum();

REASONCODE
55822004.0    245402
Name: DISPENSES, dtype: int64

In [20]:
statin_df.START_DAY.min(),statin_df.START_DAY.max()

('1952-12-07', '2021-07-20')

In [21]:
statin_df.STOP_DAY.min(),statin_df.STOP_DAY.max()

('1954-12-07', '2021-07-31')

In [22]:
#Remove fills with start before 1/1/1991

#statin_df[statin_df.START_DAY<'1991-01-01']

patient_list = [j if i<'1991-01-01' else 0 for i,j in zip(statin_df.START_DAY,statin_df.PATIENT)] 

patient_list = list(filter(None, patient_list))

#Drop the list of patients from the data from
mask = ~statin_df['PATIENT'].isin(patient_list)
statin_df = statin_df[mask]
statin_df

len(patient_list)
#len(statin_df.PATIENT.unique())

6814

In [23]:
print('unique patients:',len(statin_df.PATIENT.unique()))
print('total dispenses (1 month supply):',statin_df.DISPENSES.sum())

unique patients: 660
total dispenses (1 month supply): 104921

In [24]:
print('average dispenses per patient:',statin_df.DISPENSES.sum()/len(statin_df.PATIENT.unique()))

average dispenses per patient: 158.97121212121212

In [25]:
statin_df.head()

,PATIENT,CODE,DESCRIPTION,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION,BIRTHDATE,DEATHDATE,RACE,GENDER,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,START_DAY,STOP_DAY
0,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,10,0.20,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.0,2015-02-01,2021-01-30
1,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.0,2016-02-01,2017-01-31
2,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.0,2017-01-31,2018-01-31
3,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.0,2018-01-31,2019-01-31
4,b24e154c-14c4-8372-2b52-a466bc9b44fe,314231,Simvastatin 10 MG Oral Tablet,12,0.24,55822004.0,Hyperlipidemia,1959-05-30,NaN,white,M,28809.79,0.0,2019-01-31,2020-01-31

In [30]:
#Count of unique patients who are still alive
unique_live = len(statin_df[statin_df.DEATHDATE.isnull()].PATIENT.unique())
print('Number of unique patients still alive at time of discontinuation:',unique_live)

Number of unique patients still alive at time of discontinuation: 354

In [25]:
statin_df.to_csv('statins.csv')

In [118]:
patient.loc[0,'DEATHDATE']

nan

## Grouping the Encounters for Censor Analysis

In [115]:
## Variable Iniatiation
patient = []

#Key dates
earliest_start = []
latest_start = []
sec_to_last_stop = []
latest_stop = []
death_date = []

#Dispene variables
dispense_count = []
CODES = [259255,312961,314231]
atorv_80_count = []
simv_20_count = []
simv_10_count = []


#Demographic variables
age_at_start  = []
gender  = []
race = []


##Loop through to create lists of variables by patient
for i in range(len(unique_patients)): 
    patient = statin_df[statin_df.PATIENT == unique_patients[i]].reset_index(drop=True)
    
    #Key dates
    death_date.append(patient.loc[0,'DEATHDATE'])
    earliest_start.append(patient.loc[0,'START_DAY'])
    latest_start.append(patient.START_DAY[len(patient)-1])
    latest_stop.append(patient.STOP_DAY[len(patient)-1])
    if len(patient)>2:
        sec_to_last_stop.append(patient.STOP_DAY[len(patient)-2])
    else:
        sec_to_last_stop.append(patient.STOP_DAY[len(patient)-1])
    #Dispense info
    dispense_count.append(patient.DISPENSES.sum())
    atorv_80_count.append(patient[patient.CODE == CODES[0]].DISPENSES.sum())
    simv_20_count.append(patient[patient.CODE == CODES[1]].DISPENSES.sum())
    simv_10_count.append(patient[patient.CODE == CODES[2]].DISPENSES.sum())
    
    #Demo data
    age = (pd.to_datetime(patient.BIRTHDATE[0])-pd.to_datetime(patient.START_DAY[0]))
    age = np.round(-age.total_seconds()/365/24/60/60,0)

    age_at_start.append(age)
    
    gender.append(patient.GENDER[0])
    race.append(patient.RACE[0])
    
    #Censored patients (Death)
    
    
#Merge helper lists into a patient level data frame
hazard_df = pd.DataFrame({'patient_ID':unique_patients,
                          'earliest_start':earliest_start,
                          'latest_start':latest_start,
                          'sec_to_last_stop':sec_to_last_stop,
                          'latest_stop':latest_stop,
                          'death_date':death_date,
                          'age_at_start':age_at_start,
                          'dispense_count':dispense_count,
                          'simv_10_count':simv_10_count,
                          'simv_20_count': simv_20_count,
                          'atorv_80_count':atorv_80_count,
                          'gender':gender,
                          'race':race
                         })

In [117]:
hazard_df.head()

,patient_ID,earliest_start,latest_start,sec_to_last_stop,latest_stop,death_date,age_at_start,dispense_count,simv_10_count,simv_20_count,atorv_80_count,gender,race
0,b24e154c-14c4-8372-2b52-a466bc9b44fe,2015-02-01,2021-01-30,2021-01-30,2021-07-31,NaN,56.0,82,82,0,0,M,white
1,fd263d8e-7d79-e54c-0c5f-351a1e3635ed,2005-12-20,2020-12-16,2020-12-16,2021-07-31,NaN,44.0,190,190,0,0,F,white
2,40c7c5d7-e21d-0aec-3023-bf613f37a5f1,1995-06-02,1997-06-01,1997-06-01,2021-07-31,1998-05-01,50.0,34,34,0,0,M,white
3,b6d9f9f6-b4b0-8b31-1827-dcc141011135,1994-05-20,2000-06-23,2000-06-23,2021-07-31,2000-06-27,77.0,74,0,74,0,M,white
4,5450a2c7-c50c-ac32-81fe-425e52b21c52,2013-10-18,2020-10-16,2020-10-16,2021-07-31,NaN,48.0,94,94,0,0,M,white

79.56986301369862

80.0

In [67]:
hazard_df

,patient_ID,earliest_start,latest_start,latest_stop,death_date
0,b24e154c-14c4-8372-2b52-a466bc9b44fe,2015-02-01,2021-01-30,2021-07-31,NaN
1,fd263d8e-7d79-e54c-0c5f-351a1e3635ed,2005-12-20,2020-12-16,2021-07-31,NaN
2,40c7c5d7-e21d-0aec-3023-bf613f37a5f1,1995-06-02,1997-06-01,2021-07-31,1998-05-01
3,b6d9f9f6-b4b0-8b31-1827-dcc141011135,1994-05-20,2000-06-23,2021-07-31,2000-06-27
4,5450a2c7-c50c-ac32-81fe-425e52b21c52,2013-10-18,2020-10-16,2021-07-31,NaN
...,...,...,...,...,...
655,bb6b882d-9d3d-8ff1-54ac-e0e206420ab4,1994-05-16,2003-07-07,2021-07-31,2004-06-21
656,91dcb4fb-fe99-4235-9193-23001c49352f,2009-03-30,2017-05-15,2021-07-31,2017-07-22
657,bbd9e6e9-3815-f29e-947c-65ca93477e83,1992-10-25,2017-10-19,2021-07-31,2018-06-27
658,11d3a003-57bf-d281-60b0-8ba6a523c557,2001-11-25,2007-01-07,2007-01-07,2007-01-07
659,4c84197b-e4e9-b971-e642-52ee9bb102cf,2011-02-06,2021-03-14,2021-07-31,NaN

'2021-01-30'

In [ ]:
med_rec.START_DAY

In [ ]:
pd.to_datetime(med_rec.START_DAY)

In [ ]:
#last_range = last_record.STOP_DAY-last_record.START_DAY
if pd.isna(last_record.STOP_DAY):
    last_record.STOP_DAY,last_record.START_DAY
    if last_record.START_DAY:
        censored = True
    
else:
    last_range = last_record.STOP_DAY-last_record.START_DAY

In [ ]:
next_to_last_record.STOP_DAY,next_to_last_record.START_DAY

In [ ]:
next_to_last_record.STOP_DAY.type(),next_to_last_record.START_DAY.type()